# Source inventory mirrors Steamhammer 5.3.6 VisualStudio/UAlbertaBot.vcxproj Release|Win32.
# Explicit files exclude experimental implementations not selected by upstream.
set(STEAMHAMMER_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../steamhammer" CACHE PATH "Prepared Steamhammer 5.3.6 source")
set(STEAMHAMMER_OUTPUT_DIR "${CMAKE_BINARY_DIR}/bin" CACHE PATH "Steamhammer executable output")
set(STEAMHAMMER_SOURCE_ROOT "${STEAMHAMMER_SOURCE_DIR}/Steamhammer/Source")

add_library(SteamhammerRC STATIC
  "${STEAMHAMMER_SOURCE_DIR}/RC/Source/BitVector.cpp"
  "${STEAMHAMMER_SOURCE_DIR}/RC/Source/CA.cpp"
  "${STEAMHAMMER_SOURCE_DIR}/RC/Source/Common.cpp"
  "${STEAMHAMMER_SOURCE_DIR}/RC/Source/Input.cpp"
  "${STEAMHAMMER_SOURCE_DIR}/RC/Source/Logistic.cpp")
target_compile_features(SteamhammerRC PRIVATE cxx_std_17)
target_compile_definitions(SteamhammerRC PRIVATE WIN32 NDEBUG NOMINMAX _CRT_SECURE_NO_WARNINGS)
target_compile_options(SteamhammerRC PRIVATE /W3 /MP)

set(STEAMHAMMER_SOURCES
  "${STEAMHAMMER_SOURCE_ROOT}/Base.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Bases.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/BuildingManager.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/BuildingPilot.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/BuildingPlacer.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/BuildOrder.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/BuildOrderQueue.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/CombatSimulation.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/CombatCommander.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Common.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Dll.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Evaluator.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/FAP.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/File.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Forecast.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GameCommander.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GameRecord.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GameRecordNow.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Grid.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridAttacks.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridBuildable.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridCreep.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridDistances.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridInset.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridRoom.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridSafePath.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridTasks.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridTileRoom.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridWalk.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/GridZone.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/InformationManager.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/JSONTools.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Logger.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MacroAct.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MacroCommand.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Maker.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MapGrid.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MapPartitions.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MapTools.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroAirToAir.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroDefilers.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroDetectors.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroHighTemplar.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroIrradiated.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroLurkers.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroManager.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Config.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Micro.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroMedics.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroMelee.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroMinelaying.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroMutas.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroOverlords.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroQueens.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroRanged.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroScourge.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroStaticDefense.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroTanks.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/MicroTransports.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Moveout.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/OpeningTiming.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/OpeningTimingRecord.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/OpponentModel.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/OpponentPlan.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/OpsBoss.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/OpsStrategy.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/ParseUtils.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/PlayerSnapshot.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/ProductionGoal.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/ProductionManager.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Random.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/ResourceInfo.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/ScoutManager.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Skill.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillBases.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillBattles.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillEnemyUps.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillGasSteal.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillKit.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillMoveout.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillOpeningTiming.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SkillUnitTimings.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SpiderMineData.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Squad.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SquadData.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/SquadOrder.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/StaticDefense.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/StrategyBoss.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/StrategyBossProtoss.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/StrategyBossTerran.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/StrategyBossZerg.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/StrategyManager.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Task.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/Tasks.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/The.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/TimerManager.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/UABAssert.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/UAlbertaBotModule.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/UnitData.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/UnitUtil.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/WorkerData.cpp"
  "${STEAMHAMMER_SOURCE_ROOT}/WorkerManager.cpp"
)

add_executable(Steamhammer host.cpp ${STEAMHAMMER_SOURCES})
target_compile_features(Steamhammer PRIVATE cxx_std_17)
target_compile_definitions(Steamhammer PRIVATE WIN32 NDEBUG NOMINMAX _CRT_SECURE_NO_WARNINGS)
target_compile_options(Steamhammer PRIVATE /W3 /MP)
target_include_directories(Steamhammer PRIVATE
  "${BWAPI_SOURCE_DIR}/bwapi/include"
  "${STEAMHAMMER_SOURCE_ROOT}"
  "${STEAMHAMMER_SOURCE_DIR}/RC/Source"
  "${CMAKE_CURRENT_LIST_DIR}")
target_link_libraries(Steamhammer PRIVATE SteamhammerRC BWAPIClient BWAPIStatic)
target_link_options(Steamhammer PRIVATE /Brepro)
set_target_properties(Steamhammer PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY "${STEAMHAMMER_OUTPUT_DIR}"
  RUNTIME_OUTPUT_DIRECTORY_RELEASE "${STEAMHAMMER_OUTPUT_DIR}")