# Source lists mirror the pinned upstream Visual Studio library/client projects.
set(UALBERTABOT_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../ualbertabot" CACHE PATH "Prepared UAlbertaBot source")
set(UALBERTABOT_OUTPUT_DIR "${CMAKE_BINARY_DIR}/bin" CACHE PATH "UAlbertaBot executable output")

add_library(UabBoss STATIC
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/ActionInProgress.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/ActionSet.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/ActionType.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/ActionTypeData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BOSSAssert.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BOSSException.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BuildOrder.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BuildOrderPlot.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BOSS.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BuildingData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearch_BestResponse.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearch_BestResponseData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearch_Bucket.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearch_BucketData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearch_IntegralData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearchParameters.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearchResults.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/CombatSearch_Integral.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/Constants.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BuildOrderSearchGoal.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/DFBB_BuildOrderSearchParameters.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/DFBB_BuildOrderSearchResults.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/DFBB_BuildOrderSmartSearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/DFBB_BuildOrderStackSearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/Eval.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/GameState.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/HatcheryData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/BOSSLogger.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/JSONTools.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/NaiveBuildOrderSearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/PrerequisiteSet.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/Tools.cpp"
  "${UALBERTABOT_SOURCE_DIR}/BOSS/source/UnitData.cpp"
)

add_library(UabSparCraft STATIC
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Action.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/AllPlayers.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/AlphaBetaMove.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/AlphaBetaSearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/AnimationFrameData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Common.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/EnumData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Game.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/GameState.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Hash.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Logger.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/MoveArray.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/PlayerProperties.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_AlphaBeta.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_AttackClosest.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_AttackDPS.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_AttackWeakest.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_Cluster.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_Kiter.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_KiterDPS.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_Kiter_NOKDPS.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_NOKDPS.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_PortfolioGreedySearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_Random.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Player_UCT.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/PortfolioGreedySearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/SparCraft.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/SparCraftAssert.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/SparCraftException.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/TranspositionTable.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/UCTSearch.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/Unit.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/UnitProperties.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/UnitScriptData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/SparCraft/source/WeaponProperties.cpp"
)

add_executable(UAlbertaBot
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/AutoObserver.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BaseLocation.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BaseLocationManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BOSSManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BuildingData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BuildingManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BuildingPlacerManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BuildOrder.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/BuildOrderQueue.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/CombatSimulation.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/CombatCommander.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/Common.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/DetectorManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/DistanceMap.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/Global.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/main.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/GameCommander.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/InformationManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/JSONTools.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/Logger.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/MapTools.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/MedicManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/MeleeManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/MetaType.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/MicroManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/Config.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/Micro.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/ParseUtils.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/ProductionManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/RangedManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/ScoutManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/Squad.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/SquadData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/StrategyManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/TankManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/TimerManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/TransportManager.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/UABAssert.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/UAlbertaBotModule.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/UnitData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/UnitUtil.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/WorkerData.cpp"
  "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/source/WorkerManager.cpp"
)

foreach(target IN ITEMS UabBoss UabSparCraft UAlbertaBot)
  target_compile_features(${target} PRIVATE cxx_std_14)
  target_compile_definitions(${target} PRIVATE WIN32 NDEBUG NOMINMAX _CRT_SECURE_NO_WARNINGS)
  target_compile_options(${target} PRIVATE /W3 /MP)
  target_include_directories(${target} PRIVATE "${BWAPI_SOURCE_DIR}/bwapi/include" "${CMAKE_CURRENT_LIST_DIR}")
endforeach()
target_include_directories(UAlbertaBot PRIVATE "${UALBERTABOT_SOURCE_DIR}/UAlbertaBot/Source")
target_link_libraries(UAlbertaBot PRIVATE UabBoss UabSparCraft BWAPIClient BWAPIStatic)
target_link_options(UAlbertaBot PRIVATE /Brepro)
set_target_properties(UAlbertaBot PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY "${UALBERTABOT_OUTPUT_DIR}"
  RUNTIME_OUTPUT_DIRECTORY_RELEASE "${UALBERTABOT_OUTPUT_DIR}")
