import { compile } from 'json-schema-to-typescript'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { format } from 'oxfmt'

const root = new URL('../', import.meta.url)
const schema: unknown = JSON.parse(
  await readFile(new URL('schemas/metadata.schema.json', root), 'utf8'),
)
if (
  !schema ||
  typeof schema !== 'object' ||
  Array.isArray(schema) ||
  !('$defs' in schema) ||
  !schema.$defs ||
  typeof schema.$defs !== 'object' ||
  Array.isArray(schema.$defs)
) {
  throw new Error('Metadata schema must contain an object of definitions')
}
const names = Object.keys(schema.$defs)
const generated = await compile(
  {
    ...schema,
    title: 'MetadataTypes',
    type: 'object',
    additionalProperties: false,
    properties: Object.fromEntries(names.map(name => [name, { $ref: '#/$defs/' + name }])),
    required: names,
  },
  'MetadataTypes',
  {
    bannerComment:
      '/* Generated by pnpm gen:metadata from schemas/metadata.schema.json. Do not edit directly. */',
    unknownAny: true,
    ignoreMinAndMaxItems: true,
  },
)
const output = new URL('tools/metadata.ts', root)
const result = await format(fileURLToPath(output), generated, {
  semi: false,
  singleQuote: true,
  printWidth: 100,
  trailingComma: 'all',
})
if (result.errors.length) throw new Error(JSON.stringify(result.errors))
if (process.argv.includes('--check')) {
  if ((await readFile(output, 'utf8')) !== result.code) {
    throw new Error('Metadata types are stale; run pnpm gen:metadata')
  }
} else {
  await writeFile(output, result.code)
}
