/* Generated by pnpm gen:metadata from schemas/metadata.schema.json. Do not edit directly. */

export type Runtime =
  | {
      kind: 'native'
    }
  | {
      kind: 'java'
      major: number
      architecture: 'x86' | 'x86_64'
      /**
       * Arguments passed to Java before -jar; launch.arguments are passed to the bot afterward.
       */
      jvmArguments?: string[]
    }

export interface MetadataTypes {
  source: Source
  bot: Bot
  format: Format
  profile: Profile
  eligibility: Eligibility
  permissions: Permissions
  candidate: Candidate
  runtime: Runtime
  package: Package
  artifact: Artifact
  catalog: Catalog
  sourceLock: SourceLock
  sourceReview: SourceReview
}
export interface Source {
  id: string
  /**
   * Canonical HTTPS Git URL ending in .git, without credentials, query, or fragment; tools/validate.ts also enforces URL semantics.
   */
  repository: string
  revision: string
  patches?: {
    path: string
    sha256: string
  }[]
}
export interface Bot {
  id: string
  name: string
  description: string
  /**
   * @minItems 1
   */
  authors: {
    name: string
    url?: string
  }[]
  homepage: string
  sourceUrl: string
  /**
   * @minItems 0
   */
  playStyleTags: (
    | 'cheese'
    | 'timing-attack'
    | 'macro'
    | 'defensive'
    | 'aggressive'
    | 'harassment'
    | 'micro-heavy'
    | 'drops'
    | 'air-focused'
    | 'bio'
    | 'mech'
    | 'varied-openings'
    | 'reactive'
  )[]
  humanSkill: 'uncalibrated'
  /**
   * @minItems 0
   */
  externalRatings: {
    provider: string
    entry: string
    rating: number
    observedOn: string
    ratedVersion: string | null
    sourceUrl: string
    notes: string
  }[]
}
export interface Format {
  id: 'one-v-one' | 'teams' | 'free-for-all'
  support: 'verified' | 'experimental' | 'incompatible' | 'unverified'
  notes: string
}
export interface Profile {
  /**
   * @minItems 1
   */
  selectableRaces: ('zerg' | 'terran' | 'protoss')[]
  randomRace: 'supported' | 'unsupported' | 'unverified'
  /**
   * @minItems 1
   */
  formats: Format[]
  /**
   * @minItems 0
   */
  mapConstraints: string[]
  learning: {
    mode: 'persistent' | 'none' | 'unknown'
    notes: string
  }
}
export interface Eligibility {
  status: 'unreviewed' | 'approved' | 'restricted' | 'denied'
  evidence: string
}
export interface Permissions {
  localDistribution: Eligibility
  publicCompetition: Eligibility
}
export interface Candidate {
  schemaVersion: 1
  bot: Bot
  /**
   * @minItems 1
   */
  sourceIds: string[]
  profile: Profile
  license: {
    name: string
    sourceId: string
    path: string
    notes: string
  }
  permissions: Permissions
  compatibility: {
    status: 'unverified' | 'prototype-tested'
    bwapiVersion: '4.4.0'
    protocol: 10003
    botArchitecture: 'x86' | 'x86_64'
    /**
     * @minItems 1
     */
    gameArchitectures: ('x86' | 'x86_64')[]
    evidence: string
    /**
     * @minItems 1
     */
    limitations: string[]
  }
  build: {
    status: 'recipe-in-shieldbattery' | 'recipe-in-robotics-facility'
    repository: string
    revision: string
    instructions: string
  }
  sourceReview: SourceReview
}
export interface SourceReview {
  status: 'pending' | 'approved' | 'rejected'
  evidence: string
}
export interface Package {
  schemaVersion: 1
  botId: string
  releaseId: string
  version: string
  platform: {
    os: 'windows'
    architecture: 'x86' | 'x86_64'
  }
  runtime: Runtime
  launch: {
    entrypoint: string
    /**
     * @minItems 0
     */
    arguments: string[]
    workingDirectory: '.' | string
  }
  profile: Profile
  bwapi: {
    version: string
    protocol: number
    minimumBridgeVersion: string
  }
  /**
   * @minItems 1
   */
  sources: Source[]
  /**
   * @minItems 1
   */
  licenses: {
    name: string
    noticePath: string
  }[]
  permissions: Permissions
  modifications?: {
    modifier: string
    date: string
    summary: string
    scope: 'bot' | 'dependency'
  }[]
  /**
   * @minItems 0
   */
  writableDirectories: string[]
  build: {
    recipeSource: Source
    recipePath: string
    toolchain: string
  }
  sourceReview: SourceReview
}
export interface Artifact {
  url: string
  sha256: string
  sizeBytes: number
  manifestSha256: string
  format: 'zip'
}
export interface Catalog {
  schemaVersion: 1
  revision: number
  /**
   * @minItems 0
   */
  bots: {
    bot: Bot
    /**
     * @minItems 1
     */
    releases: {
      package: Package
      artifact: Artifact
    }[]
  }[]
}
export interface SourceLock {
  schemaVersion: 1
  /**
   * @minItems 1
   */
  sources: Source[]
}
